/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Olympic data with server-side pagination
         * @description Retrieve Olympic athlete data with support for pagination, sorting, and filtering
         */
        post: operations["getData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OlympicData: {
            athlete: string;
            age?: number;
            country?: string;
            year?: number;
            sport?: string;
            gold?: number;
            silver?: number;
            bronze?: number;
            total?: number;
        };
        OlympicGetRowsResponse: {
            rows: components["schemas"]["OlympicData"][];
            modelResponse?: components["schemas"]["ServerSideGetRowsResponse"];
        };
        /** @description Column definition sent by the grid */
        ColumnVO: {
            /**
             * @description Column identifier
             * @example country
             */
            id?: string;
            /**
             * @description Display name of the column
             * @example Country
             */
            displayName?: string;
            /**
             * @description Field name mapped to row data
             * @example country
             */
            field?: string;
            /**
             * @description Aggregation function (e.g. sum, min, max, avg, count)
             * @example sum
             * @enum {string}
             */
            aggFunc?: "sum" | "min" | "max" | "avg" | "count" | "first" | "last";
        };
        /** @description Text filter model */
        TextColumnFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            filterType: "text";
            /**
             * @description Filter operation type
             * @enum {string}
             */
            type?: "equals" | "notEqual" | "contains" | "notContains" | "startsWith" | "endsWith" | "blank" | "notBlank";
            /** @description The filter text value */
            filter?: string;
        };
        /** @description Number filter model */
        NumberColumnFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            filterType: "number";
            /** @enum {string} */
            type?: "equals" | "notEqual" | "greaterThan" | "greaterThanOrEqual" | "lessThan" | "lessThanOrEqual" | "inRange" | "blank" | "notBlank";
            /** @description The first filter value */
            filter?: number;
            /** @description The second filter value (used with inRange) */
            filterTo?: number;
        };
        /** @description Date filter model */
        DateColumnFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            filterType: "date";
            /** @enum {string} */
            type?: "equals" | "notEqual" | "greaterThan" | "lessThan" | "inRange" | "blank" | "notBlank";
            /**
             * Format: date
             * @description The start date
             */
            dateFrom?: string;
            /**
             * Format: date
             * @description The end date (used with inRange)
             */
            dateTo?: string;
        };
        /** @description Set filter model */
        SetColumnFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            filterType: "set";
            /** @description Selected filter values */
            values?: string[];
        };
        /** @description Base filter model. Use oneOf for specific filter types. */
        ColumnFilter: components["schemas"]["TextColumnFilter"] | components["schemas"]["NumberColumnFilter"] | components["schemas"]["DateColumnFilter"] | components["schemas"]["SetColumnFilter"];
        /** @description Sort model for a single column */
        SortModel: {
            /**
             * @description Column id to sort by
             * @example athlete
             */
            colId?: string;
            /**
             * @description Sort direction
             * @example asc
             * @enum {string}
             */
            sort?: "asc" | "desc";
        };
        /** @description Request object for AG Grid Server-Side Row Model */
        ServerSideGetRowsRequest: {
            /**
             * @description First row requested
             * @example 0
             */
            startRow?: number;
            /**
             * @description Last row requested (exclusive)
             * @example 100
             */
            endRow?: number;
            /** @description Row group columns */
            rowGroupCols?: components["schemas"]["ColumnVO"][];
            /** @description Value (aggregation) columns */
            valueCols?: components["schemas"]["ColumnVO"][];
            /** @description Pivot columns */
            pivotCols?: components["schemas"]["ColumnVO"][];
            /**
             * @description True if pivot mode is on, otherwise false
             * @default false
             */
            pivotMode: boolean;
            /** @description What groups the user is currently viewing (expanded group keys) */
            groupKeys?: string[];
            /** @description Filter model keyed by column id */
            filterModel?: {
                [key: string]: components["schemas"]["ColumnFilter"];
            };
            /** @description Sort model describing active sorts */
            sortModel?: components["schemas"]["SortModel"][];
        };
        /** @description Response object for AG Grid Server-Side Row Model */
        ServerSideGetRowsResponse: {
            /** @description Row data returned from the server */
            data?: {
                [key: string]: unknown;
            }[];
            /**
             * @description Total number of rows if known, or -1 if unknown
             * @example 1000
             */
            lastRow?: number;
            /** @description Pivot result column field identifiers (only used in pivot mode) */
            pivotResultColumnsFields?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Server-side request with pagination, sorting, and filter parameters */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerSideGetRowsRequest"];
            };
        };
        responses: {
            /** @description Successfully retrieved data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OlympicGetRowsResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
