/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/olympics/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Olympic data with server-side pagination
         * @description Retrieve Olympic athlete data with support for pagination, sorting, and filtering
         */
        post: operations["getData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/olympics/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all countries
         * @description Retrieve a list of all unique countries in the Olympic data
         */
        get: operations["getCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Filter model for a column */
        FilterModel: {
            /**
             * @description Type of filter
             * @example set
             */
            filterType?: string;
            /** @description Filter values */
            values?: string[];
        };
        /** @description Server-side request with pagination, sorting, and filter parameters */
        ServerSideRequest: {
            /**
             * Format: int32
             * @description Starting row index for pagination
             * @example 0
             */
            startRow?: number;
            /**
             * Format: int32
             * @description Ending row index for pagination
             * @example 100
             */
            endRow?: number;
            /** @description List of columns to sort by with sort direction */
            sortModel?: components["schemas"]["SortModel"][];
            /** @description Map of column filters */
            filterModel?: {
                [key: string]: components["schemas"]["FilterModel"];
            };
        };
        /** @description Sort model for a column */
        SortModel: {
            /**
             * @description Column ID to sort by
             * @example athlete
             */
            colId?: string;
            /**
             * @description Sort direction
             * @example asc
             * @enum {string}
             */
            sort?: "asc" | "desc";
        };
        /** @description Response object containing paginated data results */
        ServerSideResponse: {
            /**
             * @description Whether the request was successful
             * @example true
             */
            success?: boolean;
            /** @description List of data rows for the current page */
            rows?: Record<string, never>[];
            /**
             * Format: int64
             * @description Total number of rows available
             * @example 1000
             */
            lastRow?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerSideRequest"];
            };
        };
        responses: {
            /** @description Successfully retrieved data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerSideResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServerSideResponse"];
                };
            };
        };
    };
    getCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved countries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
