server.port=4001

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:olympic_winners}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:user123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# SQL Init - add id column to olympic_winners if missing
spring.sql.init.mode=always
spring.sql.init.separator=^;

# CORS Configuration
cors.allowed.origins=http://localhost:3000,http://localhost:4000

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
